GET http://localhost:3000/api/signin
Content-Type: application/json

{
    "email": "head12@gmail.com",
    "password" : "Hello#1122", 
}


###
GET http://127.0.0.1:8000/api/courses
Content-Type: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMjI4ODYzLCJpYXQiOjE3NDAyMjUyNjMsImp0aSI6IjA3YTZmYjhiY2IyNjRmMmNiYjAyMzhlYWZjNTZjMWM1IiwidXNlcl9pZCI6MX0.vcQbaNJYM_9oGkvlGJLhu3hvw6z2S0PUq0BWpr3Dp5o



### Sign Up
POST http://localhost:8000/api/signup
Content-Type: application/json

{
  "email": "hello1@gmail.com",
    "password" : "Hello#1122",
    "full_name": "Bilal"
}

### Getting the JWTToken
POST http://127.0.0.1:8000/api/token/pair
Content-Type: application/json

{
  "email": "hamza.wasym99@gmail.com",
    "password" : "4884",
    "full_name": "mr_lalo"
}




### Get Me, meaning to check the current user, ie. the user who is logged in
GET http://127.0.0.1:8000/api/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMjI4ODYzLCJpYXQiOjE3NDAyMjUyNjMsImp0aSI6IjA3YTZmYjhiY2IyNjRmMmNiYjAyMzhlYWZjNTZjMWM1IiwidXNlcl9pZCI6MX0.vcQbaNJYM_9oGkvlGJLhu3hvw6z2S0PUq0BWpr3Dp5o


### Get Users
GET http://localhost:8000/api/users/2
Content-Type: application/json
Authorization: Bearer <token>



